// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.1
// source: api/v1/clinical_record.proto

package clinicalv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClinicalRecordService_GetPatientSummary_FullMethodName   = "/vinca.clinical.v1.ClinicalRecordService/GetPatientSummary"
	ClinicalRecordService_RecordClinicalEvent_FullMethodName = "/vinca.clinical.v1.ClinicalRecordService/RecordClinicalEvent"
	ClinicalRecordService_ListClinicalEvents_FullMethodName  = "/vinca.clinical.v1.ClinicalRecordService/ListClinicalEvents"
	ClinicalRecordService_RevokeConsent_FullMethodName       = "/vinca.clinical.v1.ClinicalRecordService/RevokeConsent"
)

// ClinicalRecordServiceClient is the client API for ClinicalRecordService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClinicalRecordServiceClient interface {
	GetPatientSummary(ctx context.Context, in *GetPatientSummaryRequest, opts ...grpc.CallOption) (*PatientSummary, error)
	RecordClinicalEvent(ctx context.Context, in *RecordClinicalEventRequest, opts ...grpc.CallOption) (*ClinicalEvent, error)
	ListClinicalEvents(ctx context.Context, in *ListClinicalEventsRequest, opts ...grpc.CallOption) (*ListClinicalEventsResponse, error)
	RevokeConsent(ctx context.Context, in *RevokeConsentRequest, opts ...grpc.CallOption) (*RevokeConsentResponse, error)
}

type clinicalRecordServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClinicalRecordServiceClient(cc grpc.ClientConnInterface) ClinicalRecordServiceClient {
	return &clinicalRecordServiceClient{cc}
}

func (c *clinicalRecordServiceClient) GetPatientSummary(ctx context.Context, in *GetPatientSummaryRequest, opts ...grpc.CallOption) (*PatientSummary, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PatientSummary)
	err := c.cc.Invoke(ctx, ClinicalRecordService_GetPatientSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clinicalRecordServiceClient) RecordClinicalEvent(ctx context.Context, in *RecordClinicalEventRequest, opts ...grpc.CallOption) (*ClinicalEvent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClinicalEvent)
	err := c.cc.Invoke(ctx, ClinicalRecordService_RecordClinicalEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clinicalRecordServiceClient) ListClinicalEvents(ctx context.Context, in *ListClinicalEventsRequest, opts ...grpc.CallOption) (*ListClinicalEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListClinicalEventsResponse)
	err := c.cc.Invoke(ctx, ClinicalRecordService_ListClinicalEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clinicalRecordServiceClient) RevokeConsent(ctx context.Context, in *RevokeConsentRequest, opts ...grpc.CallOption) (*RevokeConsentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeConsentResponse)
	err := c.cc.Invoke(ctx, ClinicalRecordService_RevokeConsent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClinicalRecordServiceServer is the server API for ClinicalRecordService service.
// All implementations must embed UnimplementedClinicalRecordServiceServer
// for forward compatibility.
type ClinicalRecordServiceServer interface {
	GetPatientSummary(context.Context, *GetPatientSummaryRequest) (*PatientSummary, error)
	RecordClinicalEvent(context.Context, *RecordClinicalEventRequest) (*ClinicalEvent, error)
	ListClinicalEvents(context.Context, *ListClinicalEventsRequest) (*ListClinicalEventsResponse, error)
	RevokeConsent(context.Context, *RevokeConsentRequest) (*RevokeConsentResponse, error)
	mustEmbedUnimplementedClinicalRecordServiceServer()
}

// UnimplementedClinicalRecordServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClinicalRecordServiceServer struct{}

func (UnimplementedClinicalRecordServiceServer) GetPatientSummary(context.Context, *GetPatientSummaryRequest) (*PatientSummary, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPatientSummary not implemented")
}
func (UnimplementedClinicalRecordServiceServer) RecordClinicalEvent(context.Context, *RecordClinicalEventRequest) (*ClinicalEvent, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordClinicalEvent not implemented")
}
func (UnimplementedClinicalRecordServiceServer) ListClinicalEvents(context.Context, *ListClinicalEventsRequest) (*ListClinicalEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListClinicalEvents not implemented")
}
func (UnimplementedClinicalRecordServiceServer) RevokeConsent(context.Context, *RevokeConsentRequest) (*RevokeConsentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeConsent not implemented")
}
func (UnimplementedClinicalRecordServiceServer) mustEmbedUnimplementedClinicalRecordServiceServer() {}
func (UnimplementedClinicalRecordServiceServer) testEmbeddedByValue()                               {}

// UnsafeClinicalRecordServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClinicalRecordServiceServer will
// result in compilation errors.
type UnsafeClinicalRecordServiceServer interface {
	mustEmbedUnimplementedClinicalRecordServiceServer()
}

func RegisterClinicalRecordServiceServer(s grpc.ServiceRegistrar, srv ClinicalRecordServiceServer) {
	// If the following call panics, it indicates UnimplementedClinicalRecordServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClinicalRecordService_ServiceDesc, srv)
}

func _ClinicalRecordService_GetPatientSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPatientSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClinicalRecordServiceServer).GetPatientSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClinicalRecordService_GetPatientSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClinicalRecordServiceServer).GetPatientSummary(ctx, req.(*GetPatientSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClinicalRecordService_RecordClinicalEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordClinicalEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClinicalRecordServiceServer).RecordClinicalEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClinicalRecordService_RecordClinicalEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClinicalRecordServiceServer).RecordClinicalEvent(ctx, req.(*RecordClinicalEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClinicalRecordService_ListClinicalEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListClinicalEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClinicalRecordServiceServer).ListClinicalEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClinicalRecordService_ListClinicalEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClinicalRecordServiceServer).ListClinicalEvents(ctx, req.(*ListClinicalEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ClinicalRecordService_RevokeConsent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeConsentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClinicalRecordServiceServer).RevokeConsent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClinicalRecordService_RevokeConsent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClinicalRecordServiceServer).RevokeConsent(ctx, req.(*RevokeConsentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClinicalRecordService_ServiceDesc is the grpc.ServiceDesc for ClinicalRecordService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClinicalRecordService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vinca.clinical.v1.ClinicalRecordService",
	HandlerType: (*ClinicalRecordServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPatientSummary",
			Handler:    _ClinicalRecordService_GetPatientSummary_Handler,
		},
		{
			MethodName: "RecordClinicalEvent",
			Handler:    _ClinicalRecordService_RecordClinicalEvent_Handler,
		},
		{
			MethodName: "ListClinicalEvents",
			Handler:    _ClinicalRecordService_ListClinicalEvents_Handler,
		},
		{
			MethodName: "RevokeConsent",
			Handler:    _ClinicalRecordService_RevokeConsent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/clinical_record.proto",
}
