// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: api/v1/clinical_record.proto

package clinicalv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPatientSummaryRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PatientRun          string                 `protobuf:"bytes,1,opt,name=patient_run,json=patientRun,proto3" json:"patient_run,omitempty"`
	RequesterHospitalId string                 `protobuf:"bytes,2,opt,name=requester_hospital_id,json=requesterHospitalId,proto3" json:"requester_hospital_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetPatientSummaryRequest) Reset() {
	*x = GetPatientSummaryRequest{}
	mi := &file_api_v1_clinical_record_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientSummaryRequest) ProtoMessage() {}

func (x *GetPatientSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_clinical_record_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetPatientSummaryRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_clinical_record_proto_rawDescGZIP(), []int{0}
}

func (x *GetPatientSummaryRequest) GetPatientRun() string {
	if x != nil {
		return x.PatientRun
	}
	return ""
}

func (x *GetPatientSummaryRequest) GetRequesterHospitalId() string {
	if x != nil {
		return x.RequesterHospitalId
	}
	return ""
}

type PatientSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PatientRun        string                 `protobuf:"bytes,1,opt,name=patient_run,json=patientRun,proto3" json:"patient_run,omitempty"`
	ActiveAllergies   []string               `protobuf:"bytes,2,rep,name=active_allergies,json=activeAllergies,proto3" json:"active_allergies,omitempty"`
	ActiveDiagnoses   []string               `protobuf:"bytes,3,rep,name=active_diagnoses,json=activeDiagnoses,proto3" json:"active_diagnoses,omitempty"`
	ActiveMedications []string               `protobuf:"bytes,4,rep,name=active_medications,json=activeMedications,proto3" json:"active_medications,omitempty"`
	LastUpdate        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PatientSummary) Reset() {
	*x = PatientSummary{}
	mi := &file_api_v1_clinical_record_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientSummary) ProtoMessage() {}

func (x *PatientSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_clinical_record_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientSummary.ProtoReflect.Descriptor instead.
func (*PatientSummary) Descriptor() ([]byte, []int) {
	return file_api_v1_clinical_record_proto_rawDescGZIP(), []int{1}
}

func (x *PatientSummary) GetPatientRun() string {
	if x != nil {
		return x.PatientRun
	}
	return ""
}

func (x *PatientSummary) GetActiveAllergies() []string {
	if x != nil {
		return x.ActiveAllergies
	}
	return nil
}

func (x *PatientSummary) GetActiveDiagnoses() []string {
	if x != nil {
		return x.ActiveDiagnoses
	}
	return nil
}

func (x *PatientSummary) GetActiveMedications() []string {
	if x != nil {
		return x.ActiveMedications
	}
	return nil
}

func (x *PatientSummary) GetLastUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdate
	}
	return nil
}

type RecordClinicalEventRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PatientRun       string                 `protobuf:"bytes,1,opt,name=patient_run,json=patientRun,proto3" json:"patient_run,omitempty"`
	EventType        string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventDataJson    []byte                 `protobuf:"bytes,3,opt,name=event_data_json,json=eventDataJson,proto3" json:"event_data_json,omitempty"`
	AuthorCredential string                 `protobuf:"bytes,4,opt,name=author_credential,json=authorCredential,proto3" json:"author_credential,omitempty"`
	EventTimestamp   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=event_timestamp,json=eventTimestamp,proto3" json:"event_timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RecordClinicalEventRequest) Reset() {
	*x = RecordClinicalEventRequest{}
	mi := &file_api_v1_clinical_record_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordClinicalEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordClinicalEventRequest) ProtoMessage() {}

func (x *RecordClinicalEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_clinical_record_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordClinicalEventRequest.ProtoReflect.Descriptor instead.
func (*RecordClinicalEventRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_clinical_record_proto_rawDescGZIP(), []int{2}
}

func (x *RecordClinicalEventRequest) GetPatientRun() string {
	if x != nil {
		return x.PatientRun
	}
	return ""
}

func (x *RecordClinicalEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *RecordClinicalEventRequest) GetEventDataJson() []byte {
	if x != nil {
		return x.EventDataJson
	}
	return nil
}

func (x *RecordClinicalEventRequest) GetAuthorCredential() string {
	if x != nil {
		return x.AuthorCredential
	}
	return ""
}

func (x *RecordClinicalEventRequest) GetEventTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTimestamp
	}
	return nil
}

type ClinicalEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EventId          string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	PatientRun       string                 `protobuf:"bytes,2,opt,name=patient_run,json=patientRun,proto3" json:"patient_run,omitempty"`
	EventType        string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventDataJson    []byte                 `protobuf:"bytes,4,opt,name=event_data_json,json=eventDataJson,proto3" json:"event_data_json,omitempty"`
	AuthorCredential string                 `protobuf:"bytes,5,opt,name=author_credential,json=authorCredential,proto3" json:"author_credential,omitempty"`
	RecordedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=recorded_at,json=recordedAt,proto3" json:"recorded_at,omitempty"`
	EventTimestamp   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=event_timestamp,json=eventTimestamp,proto3" json:"event_timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClinicalEvent) Reset() {
	*x = ClinicalEvent{}
	mi := &file_api_v1_clinical_record_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClinicalEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClinicalEvent) ProtoMessage() {}

func (x *ClinicalEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_clinical_record_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClinicalEvent.ProtoReflect.Descriptor instead.
func (*ClinicalEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_clinical_record_proto_rawDescGZIP(), []int{3}
}

func (x *ClinicalEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ClinicalEvent) GetPatientRun() string {
	if x != nil {
		return x.PatientRun
	}
	return ""
}

func (x *ClinicalEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ClinicalEvent) GetEventDataJson() []byte {
	if x != nil {
		return x.EventDataJson
	}
	return nil
}

func (x *ClinicalEvent) GetAuthorCredential() string {
	if x != nil {
		return x.AuthorCredential
	}
	return ""
}

func (x *ClinicalEvent) GetRecordedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RecordedAt
	}
	return nil
}

func (x *ClinicalEvent) GetEventTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.EventTimestamp
	}
	return nil
}

type ListClinicalEventsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PatientRun      string                 `protobuf:"bytes,1,opt,name=patient_run,json=patientRun,proto3" json:"patient_run,omitempty"`
	EventTypeFilter string                 `protobuf:"bytes,2,opt,name=event_type_filter,json=eventTypeFilter,proto3" json:"event_type_filter,omitempty"`
	PageSize        int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken       string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListClinicalEventsRequest) Reset() {
	*x = ListClinicalEventsRequest{}
	mi := &file_api_v1_clinical_record_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClinicalEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClinicalEventsRequest) ProtoMessage() {}

func (x *ListClinicalEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_clinical_record_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClinicalEventsRequest.ProtoReflect.Descriptor instead.
func (*ListClinicalEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_clinical_record_proto_rawDescGZIP(), []int{4}
}

func (x *ListClinicalEventsRequest) GetPatientRun() string {
	if x != nil {
		return x.PatientRun
	}
	return ""
}

func (x *ListClinicalEventsRequest) GetEventTypeFilter() string {
	if x != nil {
		return x.EventTypeFilter
	}
	return ""
}

func (x *ListClinicalEventsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListClinicalEventsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListClinicalEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ClinicalEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClinicalEventsResponse) Reset() {
	*x = ListClinicalEventsResponse{}
	mi := &file_api_v1_clinical_record_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClinicalEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClinicalEventsResponse) ProtoMessage() {}

func (x *ListClinicalEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_clinical_record_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClinicalEventsResponse.ProtoReflect.Descriptor instead.
func (*ListClinicalEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_clinical_record_proto_rawDescGZIP(), []int{5}
}

func (x *ListClinicalEventsResponse) GetEvents() []*ClinicalEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListClinicalEventsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type RevokeConsentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientRun    string                 `protobuf:"bytes,1,opt,name=patient_run,json=patientRun,proto3" json:"patient_run,omitempty"`
	DataCategory  string                 `protobuf:"bytes,2,opt,name=data_category,json=dataCategory,proto3" json:"data_category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeConsentRequest) Reset() {
	*x = RevokeConsentRequest{}
	mi := &file_api_v1_clinical_record_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeConsentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeConsentRequest) ProtoMessage() {}

func (x *RevokeConsentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_clinical_record_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeConsentRequest.ProtoReflect.Descriptor instead.
func (*RevokeConsentRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_clinical_record_proto_rawDescGZIP(), []int{6}
}

func (x *RevokeConsentRequest) GetPatientRun() string {
	if x != nil {
		return x.PatientRun
	}
	return ""
}

func (x *RevokeConsentRequest) GetDataCategory() string {
	if x != nil {
		return x.DataCategory
	}
	return ""
}

type RevokeConsentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeConsentResponse) Reset() {
	*x = RevokeConsentResponse{}
	mi := &file_api_v1_clinical_record_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeConsentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeConsentResponse) ProtoMessage() {}

func (x *RevokeConsentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_clinical_record_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeConsentResponse.ProtoReflect.Descriptor instead.
func (*RevokeConsentResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_clinical_record_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeConsentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RevokeConsentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_v1_clinical_record_proto protoreflect.FileDescriptor

const file_api_v1_clinical_record_proto_rawDesc = "" +
	"\n" +
	"\x1capi/v1/clinical_record.proto\x12\x11vinca.clinical.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"o\n" +
	"\x18GetPatientSummaryRequest\x12\x1f\n" +
	"\vpatient_run\x18\x01 \x01(\tR\n" +
	"patientRun\x122\n" +
	"\x15requester_hospital_id\x18\x02 \x01(\tR\x13requesterHospitalId\"\xf3\x01\n" +
	"\x0ePatientSummary\x12\x1f\n" +
	"\vpatient_run\x18\x01 \x01(\tR\n" +
	"patientRun\x12)\n" +
	"\x10active_allergies\x18\x02 \x03(\tR\x0factiveAllergies\x12)\n" +
	"\x10active_diagnoses\x18\x03 \x03(\tR\x0factiveDiagnoses\x12-\n" +
	"\x12active_medications\x18\x04 \x03(\tR\x11activeMedications\x12;\n" +
	"\vlast_update\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUpdate\"\xf6\x01\n" +
	"\x1aRecordClinicalEventRequest\x12\x1f\n" +
	"\vpatient_run\x18\x01 \x01(\tR\n" +
	"patientRun\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12&\n" +
	"\x0fevent_data_json\x18\x03 \x01(\fR\reventDataJson\x12+\n" +
	"\x11author_credential\x18\x04 \x01(\tR\x10authorCredential\x12C\n" +
	"\x0fevent_timestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0eeventTimestamp\"\xc1\x02\n" +
	"\rClinicalEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vpatient_run\x18\x02 \x01(\tR\n" +
	"patientRun\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12&\n" +
	"\x0fevent_data_json\x18\x04 \x01(\fR\reventDataJson\x12+\n" +
	"\x11author_credential\x18\x05 \x01(\tR\x10authorCredential\x12;\n" +
	"\vrecorded_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"recordedAt\x12C\n" +
	"\x0fevent_timestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0eeventTimestamp\"\xa4\x01\n" +
	"\x19ListClinicalEventsRequest\x12\x1f\n" +
	"\vpatient_run\x18\x01 \x01(\tR\n" +
	"patientRun\x12*\n" +
	"\x11event_type_filter\x18\x02 \x01(\tR\x0feventTypeFilter\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"~\n" +
	"\x1aListClinicalEventsResponse\x128\n" +
	"\x06events\x18\x01 \x03(\v2 .vinca.clinical.v1.ClinicalEventR\x06events\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\\\n" +
	"\x14RevokeConsentRequest\x12\x1f\n" +
	"\vpatient_run\x18\x01 \x01(\tR\n" +
	"patientRun\x12#\n" +
	"\rdata_category\x18\x02 \x01(\tR\fdataCategory\"K\n" +
	"\x15RevokeConsentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xbb\x03\n" +
	"\x15ClinicalRecordService\x12c\n" +
	"\x11GetPatientSummary\x12+.vinca.clinical.v1.GetPatientSummaryRequest\x1a!.vinca.clinical.v1.PatientSummary\x12f\n" +
	"\x13RecordClinicalEvent\x12-.vinca.clinical.v1.RecordClinicalEventRequest\x1a .vinca.clinical.v1.ClinicalEvent\x12q\n" +
	"\x12ListClinicalEvents\x12,.vinca.clinical.v1.ListClinicalEventsRequest\x1a-.vinca.clinical.v1.ListClinicalEventsResponse\x12b\n" +
	"\rRevokeConsent\x12'.vinca.clinical.v1.RevokeConsentRequest\x1a(.vinca.clinical.v1.RevokeConsentResponseB6Z4github.com/minsal/vincula/api/v1/clinical;clinicalv1b\x06proto3"

var (
	file_api_v1_clinical_record_proto_rawDescOnce sync.Once
	file_api_v1_clinical_record_proto_rawDescData []byte
)

func file_api_v1_clinical_record_proto_rawDescGZIP() []byte {
	file_api_v1_clinical_record_proto_rawDescOnce.Do(func() {
		file_api_v1_clinical_record_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_clinical_record_proto_rawDesc), len(file_api_v1_clinical_record_proto_rawDesc)))
	})
	return file_api_v1_clinical_record_proto_rawDescData
}

var file_api_v1_clinical_record_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_v1_clinical_record_proto_goTypes = []any{
	(*GetPatientSummaryRequest)(nil),   // 0: vinca.clinical.v1.GetPatientSummaryRequest
	(*PatientSummary)(nil),             // 1: vinca.clinical.v1.PatientSummary
	(*RecordClinicalEventRequest)(nil), // 2: vinca.clinical.v1.RecordClinicalEventRequest
	(*ClinicalEvent)(nil),              // 3: vinca.clinical.v1.ClinicalEvent
	(*ListClinicalEventsRequest)(nil),  // 4: vinca.clinical.v1.ListClinicalEventsRequest
	(*ListClinicalEventsResponse)(nil), // 5: vinca.clinical.v1.ListClinicalEventsResponse
	(*RevokeConsentRequest)(nil),       // 6: vinca.clinical.v1.RevokeConsentRequest
	(*RevokeConsentResponse)(nil),      // 7: vinca.clinical.v1.RevokeConsentResponse
	(*timestamppb.Timestamp)(nil),      // 8: google.protobuf.Timestamp
}
var file_api_v1_clinical_record_proto_depIdxs = []int32{
	8, // 0: vinca.clinical.v1.PatientSummary.last_update:type_name -> google.protobuf.Timestamp
	8, // 1: vinca.clinical.v1.RecordClinicalEventRequest.event_timestamp:type_name -> google.protobuf.Timestamp
	8, // 2: vinca.clinical.v1.ClinicalEvent.recorded_at:type_name -> google.protobuf.Timestamp
	8, // 3: vinca.clinical.v1.ClinicalEvent.event_timestamp:type_name -> google.protobuf.Timestamp
	3, // 4: vinca.clinical.v1.ListClinicalEventsResponse.events:type_name -> vinca.clinical.v1.ClinicalEvent
	0, // 5: vinca.clinical.v1.ClinicalRecordService.GetPatientSummary:input_type -> vinca.clinical.v1.GetPatientSummaryRequest
	2, // 6: vinca.clinical.v1.ClinicalRecordService.RecordClinicalEvent:input_type -> vinca.clinical.v1.RecordClinicalEventRequest
	4, // 7: vinca.clinical.v1.ClinicalRecordService.ListClinicalEvents:input_type -> vinca.clinical.v1.ListClinicalEventsRequest
	6, // 8: vinca.clinical.v1.ClinicalRecordService.RevokeConsent:input_type -> vinca.clinical.v1.RevokeConsentRequest
	1, // 9: vinca.clinical.v1.ClinicalRecordService.GetPatientSummary:output_type -> vinca.clinical.v1.PatientSummary
	3, // 10: vinca.clinical.v1.ClinicalRecordService.RecordClinicalEvent:output_type -> vinca.clinical.v1.ClinicalEvent
	5, // 11: vinca.clinical.v1.ClinicalRecordService.ListClinicalEvents:output_type -> vinca.clinical.v1.ListClinicalEventsResponse
	7, // 12: vinca.clinical.v1.ClinicalRecordService.RevokeConsent:output_type -> vinca.clinical.v1.RevokeConsentResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_v1_clinical_record_proto_init() }
func file_api_v1_clinical_record_proto_init() {
	if File_api_v1_clinical_record_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_clinical_record_proto_rawDesc), len(file_api_v1_clinical_record_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_clinical_record_proto_goTypes,
		DependencyIndexes: file_api_v1_clinical_record_proto_depIdxs,
		MessageInfos:      file_api_v1_clinical_record_proto_msgTypes,
	}.Build()
	File_api_v1_clinical_record_proto = out.File
	file_api_v1_clinical_record_proto_goTypes = nil
	file_api_v1_clinical_record_proto_depIdxs = nil
}
